create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamptz default now()
);

alter table public.contacts enable row level security;

create policy "Allow public contact inserts"
on public.contacts for insert
to anon
with check (true);